name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarScanner CLI
        shell: cmd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner.bat ^
            -Dsonar.projectKey=Avi123Avi_PHP_Test_0797e005-be9a-440b-bd96-fda0ed001d71 ^
            -Dsonar.sources=. ^
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} ^
            -Dsonar.login=${{ env.SONAR_TOKEN }}
